<div class="alert alert-block alert-success">
<b>BACKPROPAGATION THROUGH LAYER</b>
</div>

In [ ]:
import numpy as np

# Initial inputs
inputs = np.array([1, 2, 3, 4])

# Initial weights and biases
weights = np.array([
    [0.1, 0.2, 0.3, 0.4],
    [0.5, 0.6, 0.7, 0.8],
    [0.9, 1.0, 1.1, 1.2]
])

biases = np.array([0.1, 0.2, 0.3])

# Learning rate
learning_rate = 0.001

# ReLU activation function and its derivative
def relu(x):
    return np.maximum(0, x)

def relu_derivative(x):
    return np.where(x > 0, 1, 0)

# # Training loop
for iteration in range(200):
    # Forward pass
    z = np.dot(weights, inputs) + biases
    a = relu(z)
    y=np.sum(a)

    # CALCULATE LOSS
    loss=y**2

    # BACKWARD PASS
    
    # GRADIENT OF LOSS WITH RESPECT TO OUTPUT y
    dL_dy=2*y

    # GRADIENT OF Y WITH RESPECT TO A
    dy_da=np.ones_like(a)

    # GRADIENT OF LOSS WITH RESPECT TO A
    dL_da=dL_dy*dy_da

    # GRADIENT OF A WITH RESPECT TO Z(RELU DERIVATIVE) 
    dA_dz=relu_derivative(a)

    # GRADIENT OF LOSS WITH RESPECT TO Z
    dL_dz=dL_da*dA_dz

    #GRADIENT OF Z WITH RESPECT TO WEIGHTS AND BIASES
    dL_dW=np.outer(dL_dz,inputs)
    dL_db=dL_dz

    #UPDATE WEIGTH AND BIASEs
    weights-=learning_rate*dL_dW
    biases-=learning_rate*dL_db

    #PRINT THE LOSS EVERY 20 ITERATIONS
    if iteration%20==0:
        print(f"Iteration {iteration} ,Loss:{loss}")

#FINAL WEIGHTS AND BIASES
print(f"Final weights: {weights}")
print(f"Final biases : {biases}")

Iteration 0 ,Loss:466.56000000000006
Iteration 20 ,Loss:5.32959636083938
Iteration 40 ,Loss:0.41191523404899866
Iteration 60 ,Loss:0.031836212079467595
Iteration 80 ,Loss:0.002460565465389601
Iteration 100 ,Loss:0.000190172825660145
Iteration 120 ,Loss:1.4698126966451542e-05
Iteration 140 ,Loss:1.1359926717815175e-06
Iteration 160 ,Loss:8.779889800154524e-08
Iteration 180 ,Loss:6.7858241357822796e-09
Final weights: [[-0.00698895 -0.01397789 -0.02096684 -0.02795579]
 [ 0.25975286  0.11950572 -0.02074143 -0.16098857]
 [ 0.53548461  0.27096922  0.00645383 -0.25806156]]
Final biases : [-0.00698895 -0.04024714 -0.06451539]


In [25]:
a=np.random.randn(3,4)
b=np.random.randn(1,4) # 

c=a+b
c.shape

(3, 4)

In [27]:
a=np.random.randn(1,3)
b=np.random.randn(3,3) # 

c=a*b
c.shape

(3, 3)

In [28]:

a=np.array([[2,1],[1,3]])
a*a

array([[4, 1],
       [1, 9]])

In [30]:


a=np.array([[1,1],[1,-1]])

b=np.array([[2],[3]])


c=a+b
c

array([[3, 3],
       [4, 2]])