In [2]:
import numpy as np

<div class="alert alert-block alert-success">
<b>Array Summation in Python</b>
</div>

![alt text](IMG/array_Summzation.jpg)

In [3]:
A=[[1,2,3],[4,5,6],[7,8,9]]
print(np.sum(A))

45


![alt text](IMG/axix=0.jpg)

In [4]:
print(np.sum(A,axis=0))

[12 15 18]


![alt text](IMG/axis=1.jpg)

In [5]:
print(np.sum(A,axis=1))

[ 6 15 24]


![alt text](IMG/keep_dim.jpg)

In [6]:
print(np.sum(A,axis=0,keepdims=True))
print(np.sum(A,axis=1,keepdims=True))

[[12 15 18]]
[[ 6]
 [15]
 [24]]


<div class="alert alert-block alert-success">
<b>Broadcasting  in Python</b>
</div>

![alt text](<IMG/Broadcasting in python.jpg>)
![alt text](IMG/example.jpg)

In [8]:
A=np.array([[1,2,3],[4,5,6],[7,8,9]])
B=np.array([1,2,3])
A+B

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])