 `BUILDING NEURAL NETWORKS FROM SCRATCH PART 1: CODING NEURONS AND LAYERS`

<div class="alert alert-block alert-success">
<b>CODING OUR FIRST NEURON: 3 INPUTS</b>
</div>

![alt text](IMG/nueron_with_3_inputs.jpg)

In [1]:
inputs=[1,2,3]
wieghts=[0.2,0.8,-0.5]
bais=2

output=(inputs[0]*wieghts[0]+inputs[1]*wieghts[1]+inputs[2]*wieghts[2]+bais)
print(output)

2.3


<div class="alert alert-block alert-warning">
SINGLE NEURON USING NUMPY
</div>

![alt text](IMG/single_neuron_with_numpy.jpg)

In [2]:
import numpy as np
Inputs=[1.0,2.0,3.0,2.5]
Weights=[0.2,0.8,-0.5,1.0]
bais=2.0
output=np.dot(Inputs,Weights)+bais
print(output)


4.8


<div class="alert alert-block alert-success">
<b>CODING OUR SECOND NEURON: 4 INPUTS</b>
</div>

![alt text](IMG/nueron_with_4_inputs.jpg)

In [3]:
inputs=[1.0,2.0,3.0,2.5]
weights=[0.2,0.8,-0.5,1.0]
bais=2.0
output=(inputs[0]*weights[0]+
        inputs[1]*weights[1]+
        inputs[2]*weights[2]+
        inputs[3]*weights[3]+
        bais)
print(output)

4.8


<div class="alert alert-block alert-success">
<b>CODING OUR FIRST LAYER</b>
</div>

![alt text](IMG/Layer_of_neuron.jpg)

In [4]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

weights1 = weights[0] #LIST OF WEIGHTS ASSOCIATED WITH 1ST NEURON : W11, W12, W13, W14
weights2 = weights[1] #LIST OF WEIGHTS ASSOCIATED WITH 2ND NEURON : W21, W22, W23, W24
weights3 = weights[2] #LIST OF WEIGHTS ASSOCIATED WITH 3RD NEURON : W31, W32, W33, W34

biases = [2, 3, 0.5]

bias1 = 2
bias2 = 3
bias3 = 0.5

outputs = [
 # Neuron 1:
 inputs[0]*weights1[0] +
 inputs[1]*weights1[1] +
 inputs[2]*weights1[2] +
 inputs[3]*weights1[3] + bias1,
 # Neuron 2:
 inputs[0]*weights2[0] +
 inputs[1]*weights2[1] +
 inputs[2]*weights2[2] +
 inputs[3]*weights2[3] + bias2,
 # Neuron 3:
 inputs[0]*weights3[0] +
 inputs[1]*weights3[1] +
 inputs[2]*weights3[2] +
 inputs[3]*weights3[3] + bias3]

print(outputs)


[4.8, 1.21, 2.385]


<div class="alert alert-block alert-danger">
USING LOOPS FOR BETTER AND EASIER CODING</div>

In [5]:
inputs = [1, 2, 3, 2.5]

##LIST OF WEIGHTS
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]

##LIST OF BIASES
biases = [2, 3, 0.5]

# Output of current layer
neuron_output = 0
layer_outputs=[]
# For each neuron
for neuron_weights, neuron_bias in zip(weights, biases):
    for weight,n_inputs in zip(neuron_weights,inputs):
         # Multiply this input by associated weight
         # and add to the neuron's output variable
        neuron_output += n_inputs*weight ## W31*X1 + W32*X2 + W33*X3 + W34*X4
   # Add bias
    neuron_output += neuron_bias ## ## W31*X1 + W32*X2 + W33*X3 + W34*X4 + B3

    layer_outputs.append(neuron_output)    
print(layer_outputs)

[4.8, 6.01, 8.395]


<div class="alert alert-block alert-warning">
LAYER OF NEURONS USING NUMPY
</div>

![alt text](<IMG/Screenshot 2024-10-25 152610.jpg>)

In [6]:
inputs = [1.0, 2.0, 3.0, 2.5]
weights = [[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]
biases = [2.0, 3.0, 0.5]

# A dot product of a matrix and a vector results in a list of dot products. 
#The np.dot() method treats the matrix as a list of vectors and performs a dot product of each of those vectors with the other vector
layer_outputs = np.dot(weights, inputs) + biases
print(layer_outputs)

[4.8   1.21  2.385]


<div class="alert alert-block alert-warning">
LAYER OF NEURONS AND BATCH OF DATA USING NUMPY
</div>

![alt text](IMG/Batch_of_inputs.jpg)

<div class="alert alert-block alert-danger">

NEED TO TAKE TRANSPOSE OF WEIGHT MATRIX</div>

![alt text](IMG/transpose_of.jpg)

In [7]:
## Batch of Inputs
inputs=[[1.0,2.0,3.0,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]
bais=[2.0,3.0,0.5]
# NOTE: We cant Transpose Lists in python so we have the convert the weights matrix into array first
outputs=np.dot(inputs,np.array(weights).T)+bais
print(outputs)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


<div class="alert alert-block alert-warning">
2 LAYERS AND BATCH OF DATA USING NUMPY
</div>

![alt text](IMG/Two_layers.jpg)
![alt text](IMG/weight_of_two_layer.jpg)

In [8]:
## Batch of Inputs
inputs=[[1.0,2.0,3.0,2.5],
        [2.0,5.0,-1.0,2.0],
        [-1.5,2.7,3.3,-0.8]]
## First Layers Weights
weights=[[0.2,0.8,-0.5,1],
         [0.5,-0.91,0.26,-0.5],
         [-0.26,-0.27,0.17,0.87]]

baise1=[2,3,0.5]

## Second Layers Weights
weights2=[[0.1,-0.14,0.5],
          [-0.5,0.12,-0.33],
          [-0.44,0.73,-0.13]
        ]
bais2=[-1,2,-0.5]

## Convert lists to numpy array
inputs_array=np.array(inputs)
weights_array=np.array(weights)
bais_array=np.array(baise1)
weight2_array=np.array(weights2)
baises2_array=np.array(bais2)

## CALCULATE THE OUTPUT FOR FIRST LAYER:
layer1_outputs=np.dot(inputs,weights_array.T)+bais_array

## CALUCLATE THE OUTPUT FOR SECOND LAYER
layer2_outputs=np.dot(layer1_outputs,weight2_array.T)+baises2_array

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


<div class="alert alert-block alert-success">
<b>DENSE LAYER CLASS</b>
</div>

![](IMG/class.jpg)
![alt text](<IMG/Class dense laywe.jpg>)
![alt text](<IMG/Initializing weights.jpg>)

In [9]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()

#DENSE LAYER:
class Layer_Dense:
    #LAYER INITIALIZATION
    def __init__(self, n_inputs, n_neurons):
        #INITIALIZE WEIGHT AND BIASES
        self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    #FORWARD PASS
    def forward(self, inputs):
        #CALUCLATE OUTPUT VALUES FROM INPUTS,WEIGHTS AND BIASES
        self.output=np.dot(inputs,self.weights)+self.biases
#CREATE DATASET
X, y = spiral_data(samples=100, classes=3)
#CREATE DENSE LAYER WITH 2 INPUT FEATURES AND # OUTPUT VALUES
dense_layer1 = Layer_Dense(2, 3)
# PERFORM a FORWARD PASS of OUR TRAINING DATA THROUGH THIS LAYER
dense_layer1.forward(X)
# LET'S SEE THE OUTPUT OF THE FIRST SAMPLES:
print(dense_layer1.output[:5])


[[ 0.0000000e+00  0.0000000e+00  0.0000000e+00]
 [-1.0475188e-04  1.1395361e-04 -4.7983500e-05]
 [-2.7414842e-04  3.1729150e-04 -8.6921798e-05]
 [-4.2188365e-04  5.2666257e-04 -5.5912682e-05]
 [-5.7707680e-04  7.1401405e-04 -8.9430439e-05]]


<div class="alert alert-block alert-success">
<b>Activation Function :Relu</b>
</div>

![alt text](IMG/Activation_functions.jpg)

In [10]:
import numpy as np
inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]
output=np.maximum(0,inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [11]:
# Relu Activation
class Activation_Relu:
    ## Forward Pass
    def forward(self, inputs):
        self.output=np.maximum(0,inputs)

<div class="alert alert-block alert-success">
<b>Activation Function :Softmax</b>
</div>

![alt text](IMG/softmax.jpg)

## STEP 1
![Step 1](<IMG/Screenshot 2024-10-27 101702.jpg>)

In [12]:
# SETP 1
exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
exp_values

AxisError: axis 1 is out of bounds for array of dimension 1

## STEP 2
![alt text](<IMG/Screenshot 2024-10-27 100913.jpg>)
![alt text](IMG/softmax_probalties.jpg)

In [ ]:
## STEP 2
probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
probabilities

array([[0.06414769, 0.17437149, 0.47399085, 0.28748998],
       [0.04517666, 0.90739747, 0.00224921, 0.04517666],
       [0.00522984, 0.34875873, 0.63547983, 0.0105316 ]])

In [ ]:
## Activation Softmax
## Activation softmax is a common activation function used in the output layer of a neural network. It is used
## to output a probability distribution over the classes. The softmax function is defined as follows:
inputs=[[1,2,3,2.5],
        [2.,5.,-1.,2],
        [-1.5,2.7,3.3,-0.8]]
## get unnormalized probabiltites
exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
## normalize them for each sample
probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
print(probabilities)
np.sum(probabilities,axis=1)


[[0.06414769 0.17437149 0.47399085 0.28748998]
 [0.04517666 0.90739747 0.00224921 0.04517666]
 [0.00522984 0.34875873 0.63547983 0.0105316 ]]


array([1., 1., 1.])

In [ ]:
# Softmax Activation Fucntion
class Activation_Softmax:
    # FORWARD PASS
    def forward(self,inputs):
        # Get unnormalized probabilities
        exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
        # Normalize them for each sample
        probabilities=exp_values/np.sum(exp_values,axis=1,keepdims=True)
        self.output=probabilities


<div class="alert alert-block alert-success">
<b>FORWARD PASS</b>
</div>

![alt text](IMG/forward_pass.jpg)
![alt text](IMG/simplicztion_forward_pass.jpg)

In [ ]:
# CREATE DATASET
X,y=spiral_data(samples=100,classes=3)
# CREATE DENSE LAYER WITH INPUT FEATURES AND  OUTPUT VALUES

dense1=Layer_Dense(2,3)
# CREATE RELU ACTIVATION FUNCTION(TO BE USED WITH DENSE LAYER)

activation1=Activation_Relu()

# CREATE DENSE LAYER WITH OUTPUT FROM PREVIOUS LAYER AND 1 OUTPUT
dense2=Layer_Dense(3,3)

# CREATE SOFTMAX ACTIVATION FUNCTION
activation2=Activation_Softmax()
# MAKE A FORWARD PASS OF OUR TRAINING DATA THROUGH THIS LAYER

dense1.forward(X)
# MAKE A FORWARD PASS THROUGH ACTIVATION FUNCTION IT TAKES OUTPUT OF FIRST DENSE LAYER HERE

activation1.forward(dense1.output)

# MAKE A FORWARD PASS THROUGH SECOND DENSE LAYER
# IT TAKES FORWARD OUTPUTS OF ACTIVATION FUNCTION OF FIRST LAYER AS INPUTS
dense2.forward(activation1.output)

# MAKE A FORWARD PASS THROUGH ACTIVATION FUNCTION IT TAKES OUTPUT OF SECOND DENSE LAYER HERE
activation2.forward(dense2.output)

# SEE THE OUTPUT OF THE FIRST FEW SAMPLES
print(activation2.output[:5])


[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]]


<div class="alert alert-block alert-success">
<b>CALCULATING NETWORK ERROR WITH LOSS </b>
</div>

![alt text](IMG/croos_entropy_loss.jpg)

<div class="alert alert-block alert-warning">
CROSS ENTROPY LOSS BUILDING BLOCKS IN PYTHON
</div>

In [ ]:
softmax_outputs=np.array([[0.7,0.1,0.2],
                          [0.1,0.5,0.4],
                          [0.02,0.9,0.08]])
class_targets=[0,1,1]
print(softmax_outputs[[0,1,2],class_targets])

[0.7 0.5 0.9]


In [ ]:
print(-np.log(softmax_outputs[range(len(softmax_outputs)),class_targets]))
neg_log=-np.log(softmax_outputs[range(len(softmax_outputs)),class_targets])
average_loss=np.mean(neg_log)
print(average_loss)

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


<div class="alert alert-block alert-warning">
IF DATA IS ONE HOT ENCODED, HOW TO EXTRACT THE RELEVANT PREDICTIONS
</div>

In [ ]:
y_true_check=np.array([
    [1,0,0],
    [0,1,0],
    [0,1,0]
])
y_pred_clipped_check=np.array([
    [0.7,0.2,0.1],
    [0.8,0.5,0.4],
    [0.02,0.9,0.08]
])
A=y_true_check*y_pred_clipped_check
B=np.sum(A,axis=1)
C=-np.log(B)
print(C)
print(np.mean(C))

[0.35667494 0.69314718 0.10536052]
0.38506088005216804


<div class="alert alert-block alert-warning">
IMPLEMENTING THE CATEGORICAL CROSS ENTROPY CLASS
</div>

<div class="alert alert-block alert-warning">
IMPLEMENTING THE LOSS CLASS
</div>

In [ ]:
# Common loss class
class Loss:
 # Calculates the data and regularization losses
 # given model output and ground truth values
 def calculate(self, output, y):
  # Calculate sample losses
  sample_losses = self.forward(output, y)
  # Calculate mean loss
  data_loss = np.mean(sample_losses)
  # Return loss
  return data_loss

In [ ]:
## Cross entropy loss
class Loss_CategoricalCrossentropy(Loss):
    # FORWAED PASS 
    def forward(self, y_pred, y_true):
        # NUMBER OF SAMPLES IN A BATCH
        samples=len(y_pred)
        # CLIP DATA TO PREVENT DIVSION BY ZERO
        # CLIP BOTH SIDES TO NOT DRAG  MEAN TOWARDS ANY VALUE
        y_pred_clipped = np.clip(y_pred, 1e-7, 1-1e-7)
        # Probabilities for target values
        # only if categorical labels
        if len(y_true.shape) ==1:
            correct_confidences=y_pred_clipped[range(samples),y_true]
        # MASK VALUE - ONLY FOR ONE HOT ENCODED LABELS
        elif len(y_true.shape)==2:
            correct_confidences=np.sum(y_pred_clipped*y_true, axis=1)
        
        neg_log_likelihoods=-np.log(correct_confidences)
        return neg_log_likelihoods

In [ ]:
class_targets=np.array([
    [1,0,0],
    [0,1,0],
    [0,1,0]
])
softmax_outputs=np.array([
    [0.7,0.2,0.1],
    [0.8,0.5,0.4],
    [0.02,0.9,0.08]
])
loss_functions=Loss_CategoricalCrossentropy()
loss=loss_functions.calculate(softmax_outputs,class_targets)
print(loss)

0.38506088005216804


<div class="alert alert-block alert-warning">
FULL CODE UPTO THIS POINT
</div>

In [ ]:
# CREATE DATA SET
X,y=spiral_data(samples=100,classes=3)

# CREATE DENSE LAYER 2 INPUTS FEATURES 3 OUTPUT VALUES
DENSE1=Layer_Dense(2,3)

# CRETAE A ACTIVATION RELU (TO BE USED WITH DENSE LAYER):
ACTIVATION1=Activation_Relu()

# CREATE A SECOND DENSE LAYER WITH 3 INPUTS FEATURES(AS WE TAKE OUTPUT OF PREVIOUS LAYER) AND OUTPUT 3 VALUES
DENSE2=Layer_Dense(3,3)

# CREATE SOFTMAX ACTIVATION(TO BE USED WITH DENSE LAYER):
ACTIVATION2=Activation_Softmax()

# CREATE LOSS FUNCTION
loss_function = Loss_CategoricalCrossentropy()

#PERFORM A FORWARD PASS OUR TRAINING DATA THROUGH THIS LAYER
DENSE1.forward(X)

# PERFORM A FORWARD PASS THROUGH ACTIVATION LAYER
# IT TAKES THE OUTPUT OF FIRST DENSE LAYER HERE
ACTIVATION1.forward(DENSE1.output)

# PERFORM A FORWARD PASS THROUGH SECOND DENSE  LAYER
# IT TAKES THE OUTPUT OF ACTIVATION LAYER HERE
DENSE2.forward(activation1.output)

# PERFORM A FORWARD PASS THROUGH ACTIVATION FUNCTION
# IT TAKES THE OUTPUT OF SECOND DENSE LAYER HERE
ACTIVATION2.forward(dense2.output)

# LET"S SEE OUTPUT OF THE  FIRST SAMPLES
print(ACTIVATION2.output[:5])

# TAKE THE OUTPUT OF SECOND DENSE LAYER HERE AND RETURN LOSS
loss=loss_function.calculate(ACTIVATION2.output,y)

# PRINT  LOSS VALUE
print("Loss:", loss)

# CALCULATE ACCURACY FROM OUPUT OF ACTIVATIONS2 AND TARGERTS
# CALCULATE VALUES ALONG FIRST AXIS
predictions=np.argmax(activation2.output,axis=1)
if len(y.shape)==2:
    y=np.argmax(y,axis=1)
accuracy=np.mean(predictions==y)
# PRINT ACCURACY
print("Accuracy:", accuracy)


[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]]
Loss: 1.0986066
Accuracy: 0.3333333333333333


<div class="alert alert-block alert-success">
<b>INTRODUCING ACCRUACY </b>
</div>

In [ ]:
import numpy as np
# Probabilities of 3 samples
softmax_outputs = np.array([[0.7, 0.2, 0.1],
 [0.5, 0.1, 0.4],
 [0.02, 0.9, 0.08]])
# Target (ground-truth) labels for 3 samples
class_targets = np.array([0, 1, 1])
# Calculate values along second axis (axis of index 1)
predictions = np.argmax(softmax_outputs, axis=1)
print(predictions)
# If targets are one-hot encoded - convert them
if len(class_targets.shape) == 2:
 class_targets = np.argmax(class_targets, axis=1)
# True evaluates to 1; False to 0
accuracy = np.mean(predictions == class_targets)
print('acc:', accuracy)

[0 0 1]
acc: 0.6666666666666666


<div class="alert alert-block alert-success">
<b>STRATEGY 1: RANDOMONLY SELECT WEIGHTS AND BAISES - DOES NOT WORK </b>
</div>

![alt text](IMG/strategy1.jpg)

In [ ]:
# CREATE DATASET
import nnfs
from nnfs.datasets import vertical_data
X,y=vertical_data(samples=100,classes=3)

# CREATE DENSE LAYER 
DENSE1=Layer_Dense(2,3) #FIRST DENSE ,2 INPUTS

# APPLYING RELU FUNCTION
ACTIVATION1=Activation_Relu()

# SECON DENSE LAYER 3 INPUTS ,# OUTPUTS
DENSE2=Layer_Dense(3,3)

# ACTIVATION SOFTMAX
ACTIVATION2=Activation_Softmax()

# CREATE A LOSS FUNCTION
loss_function=Loss_CategoricalCrossentropy()

# HEPER VAIRABLES
lowest_loss=9999999
# SOME INITAL VALUE
best_dense1_weights=dense1.weights.copy()
best_dense1_biases=dense1.biases.copy()
best_dense2_weights=dense2.weights.copy()
best_dense2_biases=dense2.biases.copy()

for iteration in range(100000):
    # GENERATE A NEW SET OF WEIGHTS FOR ITERATIONS
    dense1.weights=0.05*np.random.randn(2,3)
    dense1.biases=0.05*np.random.randn(1,3)
    dense2.weights=0.05*np.random.randn(3,3)
    dense2.biases=0.05*np.random.randn(1,3)

    # PERFORM a FROWARD PASS OF THE TRAINING DATA THROUGH THIS LAYER
    DENSE1.forward(X)
    ACTIVATION1.forward(DENSE1.output)
    DENSE2.forward(ACTIVATION1.output)
    ACTIVATION2.forward(DENSE2.output)

    # PERFORM A FORWARD PASS THROUGH ACTIVSTION FUNCTION
    # IT TAKES THE OUTPUT OF SECOND DENSE LAYER HERE AND RETURN THE LOSS
    loss=loss_function.calculate(activation2.output,y)
    
    # CALCULATE THE ACCURACY FROM OUTPUT OF ACTIVATION2 AND TARGETS
    # CALCULATE VALUES ALONG FIRST AXIS
    predictions=np.argmax(activation2.output,axis=1)
    accuracy=np.mean(predictions==y)

    # IF LOSS IS SMALLER  - PRINT AND SAVE WEIGHTS AND BAISES ASIDE
    if loss < lowest_loss:
        print(iteration)
        print("New set of weight found,iteration :",iteration,"loss :",loss,"acc :",accuracy)
        best_dense1_weights=dense1.weights.copy()
        best_dense1_biases=dense1.biases.copy()
        best_dense2_weights=dense2.weights.copy()
        best_dense2_biases=dense2.biases.copy()
        lowest_loss=loss

0
New set of weight found,iteration : 0 loss : 1.0986066 acc : 0.3333333333333333


<div class="alert alert-block alert-success">
<b>STRATEGY 2: FOR SPIRAL DATASET - DOES WORK </b>
</div>

![alt text](IMG/stragey2.jpg)

In [ ]:
# CREATE DATASET
import nnfs
from nnfs.datasets import vertical_data
X,y=vertical_data(samples=100,classes=3)

# CREATE DENSE LAYER 
DENSE1=Layer_Dense(2,3) #FIRST DENSE ,2 INPUTS

# APPLYING RELU FUNCTION
ACTIVATION1=Activation_Relu()

# SECON DENSE LAYER 3 INPUTS ,# OUTPUTS
DENSE2=Layer_Dense(3,3)

# ACTIVATION SOFTMAX
ACTIVATION2=Activation_Softmax()

# CREATE A LOSS FUNCTION
loss_function=Loss_CategoricalCrossentropy()

# HEPER VAIRABLES
lowest_loss=9999999
# SOME INITAL VALUE
best_dense1_weights=dense1.weights.copy()
best_dense1_biases=dense1.biases.copy()
best_dense2_weights=dense2.weights.copy()
best_dense2_biases=dense2.biases.copy()

for iteration in range(100000):
    # GENERATE A NEW SET OF WEIGHTS FOR ITERATIONS
    dense1.weights+=0.05*np.random.randn(2,3)
    dense1.biases+=0.05*np.random.randn(1,3)
    dense2.weights+=0.05*np.random.randn(3,3)
    dense2.biases+=0.05*np.random.randn(1,3)

    # PERFORM a FROWARD PASS OF THE TRAINING DATA THROUGH THIS LAYER
    DENSE1.forward(X)
    ACTIVATION1.forward(DENSE1.output)
    DENSE2.forward(ACTIVATION1.output)
    ACTIVATION2.forward(DENSE2.output)

    # PERFORM A FORWARD PASS THROUGH ACTIVSTION FUNCTION
    # IT TAKES THE OUTPUT OF SECOND DENSE LAYER HERE AND RETURN THE LOSS
    loss=loss_function.calculate(activation2.output,y)
    
    # CALCULATE THE ACCURACY FROM OUTPUT OF ACTIVATION2 AND TARGETS
    # CALCULATE VALUES ALONG FIRST AXIS
    predictions=np.argmax(activation2.output,axis=1)
    accuracy=np.mean(predictions==y)

    # IF LOSS IS SMALLER  - PRINT AND SAVE WEIGHTS AND BAISES ASIDE
    if loss < lowest_loss:
        print(iteration)
        print("New set of weight found,iteration :",iteration,"loss :",loss,"acc :",accuracy)
        best_dense1_weights=dense1.weights.copy()
        best_dense1_biases=dense1.biases.copy()
        best_dense2_weights=dense2.weights.copy()
        best_dense2_biases=dense2.biases.copy()
        lowest_loss=loss

0
New set of weight found,iteration : 0 loss : 1.0986066 acc : 0.3333333333333333


<div class="alert alert-block alert-success">
<b>Back Progation For Single Nueruon</b>
</div>

![alt text](IMG/Backprogation.jpg)

In [ ]:
import numpy as np

## INTIAL PARAMETERS
weights=np.array([-3.0,-1.0,2.0])
bias=1.0
inputs=np.array([1.0,-2.0,3.0])
target_output=0.0
learning_rate=0.001
def relu(x):
    return np.maximum(0,x)
def relu_derivative(x):
    return np.where(x>0,1.0,0.0)
for iteration in range(20):
    
    #FORWARD PASS
    linear_output=np.dot(weights,inputs)+bias
    output=relu(linear_output)
    loss=(output-target_output) ** 2

    #BACKWARD PASS
    dloss_doutput=2*(output-target_output)
    doutput_dlinear=relu_derivative(dloss_doutput)
    dlinear_dweights=inputs
    dlinear_dbias=1.0

    dloss_dlinear=dloss_doutput * doutput_dlinear
    dloss_dweight=dloss_dlinear * dlinear_dweights
    dloss_bias=dloss_dlinear * dlinear_dbias

    #UPDATE WEIGHTS AND BIAS
    weights-=learning_rate*dloss_dweight
    bias-=learning_rate*dloss_bias

    #PRINT THE LOSS FOR THIS ITERATION
    print(f"Iteration {iteration+1},Loss: {loss}")
print("final weights",weights)
print("Final bais",bias)


Iteration 1,Loss: 36.0
Iteration 2,Loss: 33.872397424621624
Iteration 3,Loss: 31.87054345809546
Iteration 4,Loss: 29.98699091998773
Iteration 5,Loss: 28.214761511794592
Iteration 6,Loss: 26.54726775906168
Iteration 7,Loss: 24.978326552541866
Iteration 8,Loss: 23.5021050739742
Iteration 9,Loss: 22.11313179151597
Iteration 10,Loss: 20.806246424284897
Iteration 11,Loss: 19.576596334671486
Iteration 12,Loss: 18.41961908608719
Iteration 13,Loss: 17.33101994032309
Iteration 14,Loss: 16.306757070164853
Iteration 15,Loss: 15.343027506224132
Iteration 16,Loss: 14.436253786815284
Iteration 17,Loss: 13.583071280700132
Iteration 18,Loss: 12.780312744165439
Iteration 19,Loss: 12.024995767388878
Iteration 20,Loss: 11.314319082257104
final weights [-3.18248226 -0.63503547  1.45255321]
Final bais 0.8175177371478247


<div class="alert alert-block alert-success">
<b>ADDING THE BACKWARD METHOD IN THE RELU ACTIVATION CLASS</b>
</div>

![alt text](<IMG/backprogration on the relu.jpg>)

In [13]:
# Relu Activation
class Activation_Relu:
    ## Forward Pass
    def forward(self, inputs):
        self.output=np.maximum(0,inputs)
    # BACKWARD PASS
    def backward(self,dvalues):
        #SINCE WE NEED TO MODITFY THE ORIGINAL VARIABLE
        # LET MAKE A COPY OF THE VALUES
        self.dinputs=dvalues.copy()
        # ZERO GRADIENT WHERE INPUT VALUES WERE NEGATIVE
        self.dinputs[self.inputs<=0]=0

In [ ]:
# CROSS ENTROPY LOSS
class Loss_CategoricalCrossentropy(Loss):
    #BACKWARD PASS
    def backward(self,dvalues,y_true):
        #NUMBER OF SAMPLES
        samples = len(dvalues)
        # NUMBER OF LABELS IN EVERY SAMPLE
        # WE WILL USE THE FIRST SAMPLE TO COUNT THEM
        labels=len(dvalues[0])
        # IF LABELS ARE SPARSE,TURN THEM INTO ONE-HOT VECTOR
        if len(y_true.shape)==1:
            y_true=np.eye(labels)[y_true]
            # CALCULATE GRADIENT
            self.dinputs=-y_true/dvalues
            # NORMALIZE
            self.dinputs=self.dinputs/samples

         