<div class="alert alert-block alert-success">
<b>GRADIENT LOSS WITH WIEGHTS</b>
</div>

![alt text](IMG/gradientwrtweights.jpg)

In [3]:
import numpy as np
# PASSED IN GRADIENT FROM THE NEXT LAYER
# FOR THE PURPOSE OF THIS WE ARE GOING TO USE AN ARRAY OF AN INCREMENTAL GRADIENT VALUES
dvalues=np.array([[1.,1.,1.],
[2.,2.,2.],
[3.,3.,3.]])
#WE SET # SETS OF INPUTS SAMPLES
inputs=np.array([[1,2,3,2.5],[2.,5.,-1,2],[-1.5,2.7,3.3,-.8]])
# SUM WEIGHTS OF GIVEN INPUTS
# AND MULTIPLY BY THE PASSED IN GRADIENT FOR THIS NEURON
dwieghts=np.dot(inputs.T,dvalues)
dwieghts

array([[ 0.5,  0.5,  0.5],
       [20.1, 20.1, 20.1],
       [10.9, 10.9, 10.9],
       [ 4.1,  4.1,  4.1]])

<div class="alert alert-block alert-warning">
GRADIENTS OF THE LOSS WITH RESPECT TO BIASES
</div>

![alt text](IMG/gradientwrtbiases.jpg)

In [5]:
# ONE BIAS FOR EACH NEURON
# BIASES ARE THE ROW VECTOR WITH A SHAPE (1,NUERONS)
biases=np.array([2,3,0.5])
# dbiases - sum values do thsi over samples first axis, keepdims
# since this default will produce a plain list
dbiases=np.sum(dvalues,axis=0,keepdims=True)
print(dbiases)

[[6. 6. 6.]]


<div class="alert alert-block alert-warning">
GRADIENTS OF THE LOSS WITH RESPECT TO INPUTS
</div>

![alt text](IMG/graidentwrtinput.jpg)

In [6]:
import numpy as np
# Passed-in gradient from the next layer
# for the purpose of this example we're going to use
# an array of an incremental gradient values
dvalues = np.array([[1., 1., 1.],
 [2., 2., 2.],
 [3., 3., 3.]])
# We have 3 sets of weights - one set for each neuron
# we have 4 inputs, thus 4 weights
# recall that we keep weights transposed
weights = np.array([[0.2, 0.8, -0.5, 1],
 [0.5, -0.91, 0.26, -0.5],
 [-0.26, -0.27, 0.17, 0.87]]).T
# sum weights of given input
# and multiply by the passed-in gradient for this neuron
dinputs = np.dot(dvalues, weights.T)
print(dinputs)

[[ 0.44 -0.38 -0.07  1.37]
 [ 0.88 -0.76 -0.14  2.74]
 [ 1.32 -1.14 -0.21  4.11]]
