#### Understanding Vectorization

- Vectorization eliminates the need for explicit for loops, significantly speeding up computations. This is especially beneficial in deep learning applications.
- For example, in logistic regression, using a vectorized approach to compute ( Z = W^T X + B ) is much faster than a non-vectorized implementation.

In [1]:
import numpy as np
a=np.array([1,2,3,4])
print(a)  # prints: [1 2 3 4]

[1 2 3 4]


In [2]:
import time

a=np.random.random(10000)
b=np.random.random(10000)
tic=time.time()
c=np.dot(a,b)
toc=time.time()
print(c)
print("Vectorized version "+str(1000*(toc-tic))+"ms")


2487.7007210018874
Vectorized version 0.0ms


In [3]:
c=0
tic=time.time()
for i in range(10000):
    c+=a[i]*b[i]
toc=time.time()
print(c)
print("For Loop "+str(1000*(toc-tic))+"ms")


2487.700721001875
For Loop 4.65846061706543ms


## Broadcasting 

In [7]:
A=np.array([[56.0,0.0,4.4,68.0],
          [1.2,104.0,52.0,8.0],
          [1.8,135.0,99.0,0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [9]:
cal=A.sum(axis=0)
cal

array([ 59. , 239. , 155.4,  76.9])

In [10]:
cal.reshape(1,4)

array([[ 59. , 239. , 155.4,  76.9]])

In [14]:
percentage=100*A/(cal.reshape(1,4))
percentage

array([[94.91525424,  0.        ,  2.83140283, 88.42652796],
       [ 2.03389831, 43.51464435, 33.46203346, 10.40312094],
       [ 3.05084746, 56.48535565, 63.70656371,  1.17035111]])