In [ ]:
## CREATE MODEL CLASS
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out
        

: 

In [ ]:
# CREATE DATASET
features=torch.rand(10,5)
# CREATE MODEL
model=Model(features.shape[1])
# CALL MODEL FOR FORWARD PASS
model(features)

: 

In [ ]:
model.linear.weight

: 

In [ ]:
model.linear.bias

: 

In [ ]:
!pip install torchinfo

: 

In [1]:
from torchinfo import summary
summary(model,input_size=(10,5))

c:\Users\ayush\AppData\Local\Programs\Python\Python39\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


NameError: name 'model' is not defined

In [13]:
## CREATE MODEL CLASS
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.linear1 = nn.Linear(num_features, 3)
        self.relu=nn.ReLU()
        self.linear2=nn.Linear(3,1)
        self.sigmoid=nn.Sigmoid()
    def forward(self,features):
        out=self.linear1(features)
        out=self.relu(out)
        out=self.linear2(out)
        out=self.sigmoid(out)
        return out
        

In [14]:
# CREATE DATASET
features=torch.rand(10,5)
# CREATE MODEL
model=Model(features.shape[1])
# CALL MODEL FOR FORWARD PASS
model(features)

tensor([[0.4839],
        [0.4505],
        [0.4730],
        [0.4869],
        [0.4927],
        [0.4642],
        [0.4953],
        [0.4969],
        [0.4922],
        [0.4578]], grad_fn=<SigmoidBackward0>)

In [16]:
## SHOW MODEL WEIGHTS
model.linear1.weight

Parameter containing:
tensor([[ 0.3796,  0.3391,  0.3507, -0.2064,  0.3698],
        [-0.0382, -0.4002,  0.0467, -0.4009,  0.0893],
        [ 0.2216,  0.3525, -0.4280, -0.4315, -0.3670]], requires_grad=True)

In [18]:
## CREATE MODEL CLASS
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self, num_features):
        super().__init__()
        self.network=nn.Sequential(
        nn.Linear(num_features, 3),
        nn.ReLU(),
        nn.Linear(3,1),
        nn.Sigmoid())
    def forward(self,features):
        out=self.network(features)
        return out
        

In [19]:
# CREATE DATASET
features=torch.rand(10,5)
# CREATE MODEL
model=Model(features.shape[1])
# CALL MODEL FOR FORWARD PASS
model(features)

tensor([[0.5611],
        [0.5278],
        [0.5713],
        [0.4643],
        [0.5160],
        [0.5258],
        [0.4792],
        [0.4665],
        [0.4514],
        [0.5097]], grad_fn=<SigmoidBackward0>)

In [2]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')
df.head()

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0    842302         M        17.99         10.38          122.80     1001.0   
1    842517         M        20.57         17.77          132.90     1326.0   
2  84300903         M        19.69         21.25          130.00     1203.0   
3  84348301         M        11.42         20.38           77.58      386.1   
4  84358402         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
0  ...          17.33           184.60      2019.0            0.1622   
1  ...          23.41           158.80      1956.0            0.1238   
2  ...          25.53           152.50      1709.0            0.1444   
3  ...          26.50            98.87       567.7            0.2098   
4  ...          16.67           152.20      1575.0            0.1374   

   compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
0             0.6656           0.7119                0.2654          0.4601   
1             0.1866           0.2416                0.1860          0.2750   
2             0.4245           0.4504                0.2430          0.3613   
3             0.8663           0.6869                0.2575          0.6638   
4             0.2050           0.4000                0.1625          0.2364   

   fractal_dimension_worst  Unnamed: 32  
0                  0.11890          NaN  
1                  0.08902          NaN  
2                  0.08758          NaN  
3                  0.17300          NaN  
4                  0.07678          NaN  

[5 rows x 33 columns]

In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=['id', 'Unnamed: 32'], inplace= True)

In [6]:
df.head()

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38          122.80     1001.0   
1         M        20.57         17.77          132.90     1326.0   
2         M        19.69         21.25          130.00     1203.0   
3         M        11.42         20.38           77.58      386.1   
4         M        20.29         14.34          135.10     1297.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0          0.11840           0.27760          0.3001              0.14710   
1          0.08474           0.07864          0.0869              0.07017   
2          0.10960           0.15990          0.1974              0.12790   
3          0.14250           0.28390          0.2414              0.10520   
4          0.10030           0.13280          0.1980              0.10430   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33           184.60   
1         0.1812  ...         24.99          23.41           158.80   
2         0.2069  ...         23.57          25.53           152.50   
3         0.2597  ...         14.91          26.50            98.87   
4         0.1809  ...         22.54          16.67           152.20   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   
1      1956.0            0.1238             0.1866           0.2416   
2      1709.0            0.1444             0.4245           0.4504   
3       567.7            0.2098             0.8663           0.6869   
4      1575.0            0.1374             0.2050           0.4000   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                  0.11890  
1                0.1860          0.2750                  0.08902  
2                0.2430          0.3613                  0.08758  
3                0.2575          0.6638                  0.17300  
4                0.1625          0.2364                  0.07678  

[5 rows x 31 columns]

### train test split

In [7]:
X_train, X_test, y_train, y_test = train_test_split(df.iloc[:, 1:], df.iloc[:, 0], test_size=0.2)

### scaling

In [8]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [9]:
X_train

array([[ 0.32084371,  0.79002637,  0.30527003, ...,  0.46186265,
        -0.57262387, -0.85586055],
       [ 0.01452128, -0.27501528, -0.05322243, ..., -0.606448  ,
        -0.44478096, -0.40478926],
       [-0.65331682, -0.15203661, -0.5837753 , ...,  0.56529522,
         2.95104649,  2.96973467],
       ...,
       [-0.46014051, -0.70428043, -0.45123688, ..., -0.47627073,
         0.38459996, -0.47819473],
       [-0.68919242, -0.50240979, -0.71351923, ..., -0.0951956 ,
        -0.54705529, -0.71277308],
       [-0.56500765, -0.30750021, -0.56940366, ..., -0.87832789,
        -0.81232934, -0.3765973 ]])

In [10]:
y_train

91     M
298    B
31     M
392    M
437    B
      ..
140    B
182    M
502    B
187    B
480    B
Name: diagnosis, Length: 455, dtype: object

### Label Encoding

In [11]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [12]:
y_train

array([1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0,
       1, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0,
       1, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1,
       0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,

### Numpy arrays to PyTorch tensors

In [13]:
X_train_tensor = torch.from_numpy(X_train.astype(np.float32))
X_test_tensor = torch.from_numpy(X_test.astype(np.float32))
y_train_tensor = torch.from_numpy(y_train.astype(np.float32))
y_test_tensor = torch.from_numpy(y_test.astype(np.float32))

In [14]:
X_train_tensor.shape

torch.Size([455, 30])

In [15]:
y_train_tensor.shape

torch.Size([455])

### Defining the model

In [16]:
import torch.nn as nn

class MySimpleNN(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features, 1)
        self.sigmoid=nn.Sigmoid()

    def forward(self,features):
        out=self.linear(features)
        out=self.sigmoid(out)
        return out
        

### Important Parameters

In [17]:
learning_rate = 0.1
epochs = 25

In [18]:
# define loss function
loss_function = nn.BCELoss()

### Training Pipeline

In [19]:
# create model
model = MySimpleNN(X_train_tensor.shape[1])

# define optimizer
optimizer = torch.optim.SGD(model.parameters(), lr=learning_rate)

# define loop
for epoch in range(epochs):

  # forward pass
  y_pred = model(X_train_tensor)

  # loss calculate
  loss = loss_function(y_pred, y_train_tensor.view(-1,1))

  # clear gradients
  optimizer.zero_grad()

  # backward pass
  loss.backward()

  # parameters update
  optimizer.step()

  # print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')

Epoch: 1, Loss: 0.4756607115268707
Epoch: 2, Loss: 0.400147020816803
Epoch: 3, Loss: 0.3520054817199707
Epoch: 4, Loss: 0.31818485260009766
Epoch: 5, Loss: 0.2928539514541626
Epoch: 6, Loss: 0.2730132043361664
Epoch: 7, Loss: 0.2569524645805359
Epoch: 8, Loss: 0.24361954629421234
Epoch: 9, Loss: 0.23232871294021606
Epoch: 10, Loss: 0.222612202167511
Epoch: 11, Loss: 0.21413898468017578
Epoch: 12, Loss: 0.20666758716106415
Epoch: 13, Loss: 0.2000173032283783
Epoch: 14, Loss: 0.1940499097108841
Epoch: 15, Loss: 0.18865765631198883
Epoch: 16, Loss: 0.18375517427921295
Epoch: 17, Loss: 0.1792738288640976
Epoch: 18, Loss: 0.17515766620635986
Epoch: 19, Loss: 0.17136070132255554
Epoch: 20, Loss: 0.16784453392028809
Epoch: 21, Loss: 0.16457700729370117
Epoch: 22, Loss: 0.1615307778120041
Epoch: 23, Loss: 0.15868261456489563
Epoch: 24, Loss: 0.15601247549057007
Epoch: 25, Loss: 0.15350301563739777


### Evaluation

In [20]:
# model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  accuracy = (y_pred == y_test_tensor).float().mean()
  print(f'Accuracy: {accuracy.item()}')


Accuracy: 0.5769467353820801
