In [1]:
import torch
print(torch.__version__)


2.5.1+cu121


In [2]:
if torch.cuda.is_available():
    print("CUDA is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("CUDA is not available")

CUDA is available
Using GPU: Tesla T4


# CREATE A TENSOR

In [4]:
## USING EMPTY
a=torch.empty((2,3))
a

tensor([[9.1624e-01, 3.0925e-41, 7.7673e+00],
        [3.0925e-41, 7.7682e+00, 3.0925e-41]])

In [5]:
# CHECK TYPE
type(a)

torch.Tensor

In [6]:
# USING ZEROS
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [7]:
# USING ONES
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [8]:
# USING RAND
torch.rand(2,3)

tensor([[0.5100, 0.9470, 0.4567],
        [0.7743, 0.3650, 0.8686]])

In [11]:
torch.rand(2,3)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

In [9]:
# USE OF SEED
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [10]:
torch.manual_seed(100)
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [12]:
# USING TENSOR
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [16]:
# OTHER WAYS

# ARANGE
print("USING ARANGE -->",torch.arange(1,10,2))

# LINSPACE
print("USING LINSPACE -->",torch.linspace(0,10,10))

# USING EYE
print("USING EYE -->",torch.eye(3))

# USING FULL
print("USING FULL -->",torch.full((2,3),5))


USING ARANGE --> tensor([1, 3, 5, 7, 9])
USING LINSPACE --> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
USING EYE --> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
USING FULL --> tensor([[5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [18]:
x=torch.tensor([[1,2,3],[4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [19]:
x.shape

torch.Size([2, 3])

In [20]:
torch.empty_like(x)

tensor([[    133634131545488,      94786723313904,                   0],
        [                  0,                   0, 7310593858020254331]])

In [21]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [22]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [23]:
torch.rand_like(x)

RuntimeError: "check_uniform_bounds" not implemented for 'Long'

In [30]:
torch.rand_like(x,dtype=torch.float32)

tensor([[0.7118, 0.7876, 0.4183],
        [0.9014, 0.9969, 0.7565]])

# TENSOR DATA TYPES

In [25]:
## FIND DATA TYPE
x.dtype

torch.int64

In [26]:
## ASSIGN DATA DTYPE
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [28]:
## USING TO ()
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [29]:
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

# MATHEMATICAL OPERATIONS


1 SCALER OPERATIONS

In [31]:
x=torch.rand(2,2)
x

tensor([[0.2239, 0.3023],
        [0.1784, 0.8238]])

In [32]:
# ADDITION
print(x+2)
# SUBTRACTION
print(x-2)
# DIVISION
print(x/2)
# MULTIPICATION
print(x*2)
# INT DIVISION
print((x*100)/3)
# MOD
print(((x*100//3))%2)
# POWER
print(x**2)

tensor([[2.2239, 2.3023],
        [2.1784, 2.8238]])
tensor([[-1.7761, -1.6977],
        [-1.8216, -1.1762]])
tensor([[0.1119, 0.1512],
        [0.0892, 0.4119]])
tensor([[0.4478, 0.6047],
        [0.3568, 1.6477]])
tensor([[ 7.4631, 10.0782],
        [ 5.9473, 27.4615]])
tensor([[1., 0.],
        [1., 1.]])
tensor([[0.0501, 0.0914],
        [0.0318, 0.6787]])


2. ELEMENTWISE OPERATIONS

In [33]:
a=torch.rand(2,3)
b=torch.rand(2,3)
print(a)
print(b)

tensor([[0.5557, 0.9770, 0.4440],
        [0.9478, 0.7445, 0.4892]])
tensor([[0.2426, 0.7003, 0.5277],
        [0.2472, 0.7909, 0.4235]])


In [34]:
# ADD
print(a+b)
# SUB
print(a-b)
# DIV
print(a/b)
#POWER
print(a**b)
# MOD
print(a%b)

tensor([[0.7983, 1.6774, 0.9717],
        [1.1950, 1.5354, 0.9127]])
tensor([[ 0.3132,  0.2767, -0.0837],
        [ 0.7007, -0.0464,  0.0657]])
tensor([[2.2912, 1.3951, 0.8415],
        [3.8346, 0.9413, 1.1552]])
tensor([[0.8672, 0.9839, 0.6515],
        [0.9868, 0.7919, 0.7388]])
tensor([[0.0706, 0.2767, 0.4440],
        [0.2063, 0.7445, 0.0657]])


In [36]:
c=torch.tensor([-1,-2,3,4])
c

tensor([-1, -2,  3,  4])

In [37]:
# ABS
torch.abs(c)

tensor([1, 2, 3, 4])

In [38]:
# NEGATIVE
torch.neg(c)

tensor([ 1,  2, -3, -4])

In [39]:
d=torch.tensor([1.9,2.3,3.7,4.4])
d

tensor([1.9000, 2.3000, 3.7000, 4.4000])

In [40]:
# ROUND
torch.round(d)

tensor([2., 2., 4., 4.])

In [41]:
# CEIL
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [42]:
# FLOOR
torch.floor(d)

tensor([1., 2., 3., 4.])

In [43]:
# CLAMP
torch.clamp(d,min=2,max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

3 .REDUCTION OPERATIONS

In [47]:
e=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [48]:
# SUM
print(torch.sum(e))
# ALONG THE COLUMNS WISE
print(torch.sum(e,dim=0))
# ALONG THE ROWS WISE
print(torch.sum(e,dim=1))

tensor(42.)
tensor([14., 16., 12.])
tensor([17., 25.])


In [50]:
# MEAN
print(torch.mean(e))
# MEAN ACROSS COL
print(torch.mean(e,dim=0))
# MEAN ACROSS ROW
print(torch.mean(e,dim=1))


tensor(7.)
tensor([7., 8., 6.])
tensor([5.6667, 8.3333])


In [51]:
# MEDIAN
torch.median(e)

tensor(7.)

In [52]:
# MAX AND MIN
print(torch.max(e))
print(torch.min(e))


tensor(9.)
tensor(5.)


In [53]:
# PRODUCT
torch.prod(e)

tensor(99225.)

In [54]:
# STANDARAD DEVIATION
torch.std(e)

tensor(1.7889)

In [55]:
# VARIANCE
torch.var(e)

tensor(3.2000)

In [59]:
e

tensor([[5., 7., 5.],
        [9., 9., 7.]])

In [57]:
# AGRMAX
torch.argmax(e)

tensor(3)

In [58]:
# ARGMIN
torch.argmin(e)

tensor(0)

4. MATRIX OPERATIONS

In [60]:
f=torch.randint(size=(2,3),low=0,high=10)
g=torch.randint(size=(3,2),low=0,high=10)
print(f)
print(g)

tensor([[5, 9, 8],
        [9, 7, 9]])
tensor([[2, 6],
        [7, 7],
        [8, 3]])


In [61]:
# MATRIX MULTIPICATION
torch.matmul(f,g)

tensor([[137, 117],
        [139, 130]])

In [62]:
vector1=torch.tensor([1,2])
vector2=torch.tensor([3,4])
# DOT PRODUCT
torch.dot(vector1,vector2)

tensor(11)

In [63]:
f

tensor([[5, 9, 8],
        [9, 7, 9]])

In [64]:
# TRANSPOSE
torch.transpose(f,0,1)

tensor([[5, 9],
        [9, 7],
        [8, 9]])

In [68]:
h=torch.randint(size=(3,3),low=0,high=10,dtype=torch.float32)
h

tensor([[2., 9., 5.],
        [0., 4., 2.],
        [7., 1., 1.]])

In [70]:
# DETERMINANT
torch.det(h)

tensor(-10.0000)

In [71]:
# INVERSE
torch.inverse(h)

tensor([[-0.2000,  0.4000,  0.2000],
        [-1.4000,  3.3000,  0.4000],
        [ 2.8000, -6.1000, -0.8000]])

5. COMPARSION OPERATIONS

In [72]:
i=torch.randint(size=(2,3),low=0,high=10)
j=torch.randint(size=(2,3),low=0,high=10)
print(i)
print(j)

tensor([[5, 4, 4],
        [1, 1, 2]])
tensor([[4, 7, 2],
        [5, 6, 1]])


In [75]:
# GREATER THAN
print(i>j)
# LESS THAN
print(i<j)
# EQUAL TO
print(i==j)
# GREATER THAN EQUAL TO
print(i>=j)
# LESS THAN EQUAL TO
print(i<=j)
# NOT EQUAL TO
print(i!=j)


tensor([[ True, False,  True],
        [False, False,  True]])
tensor([[False,  True, False],
        [ True,  True, False]])
tensor([[False, False, False],
        [False, False, False]])
tensor([[ True, False,  True],
        [False, False,  True]])
tensor([[False,  True, False],
        [ True,  True, False]])
tensor([[True, True, True],
        [True, True, True]])


# SPECIAL FUNCTIONS

In [82]:
k=torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
k

tensor([[1., 0., 2.],
        [1., 2., 7.]])

In [77]:
# LOG
torch.log(k)

tensor([[1.3863, 1.6094, 1.7918],
        [2.1972, 0.6931, 1.0986]])

In [78]:
# EXP
torch.exp(k)

tensor([[5.4598e+01, 1.4841e+02, 4.0343e+02],
        [8.1031e+03, 7.3891e+00, 2.0086e+01]])

In [79]:
# SQRT
torch.sqrt(k)

tensor([[2.0000, 2.2361, 2.4495],
        [3.0000, 1.4142, 1.7321]])

In [80]:
# SIGMOID
torch.sigmoid(k)

tensor([[0.9820, 0.9933, 0.9975],
        [0.9999, 0.8808, 0.9526]])

In [83]:
# SOFTMAX
torch.softmax(k,dim=0)

tensor([[0.5000, 0.1192, 0.0067],
        [0.5000, 0.8808, 0.9933]])

In [85]:
k

tensor([[1., 0., 2.],
        [1., 2., 7.]])

In [84]:
# RELU
torch.relu(k)

tensor([[1., 0., 2.],
        [1., 2., 7.]])

# INPLACE OPERATIONS

In [87]:
m=torch.rand(size=(2,3))
n=torch.rand(size=(2,3))
print(m)
print(n)


tensor([[0.9112, 0.4847, 0.9436],
        [0.3904, 0.2499, 0.3206]])
tensor([[0.9753, 0.7582, 0.6688],
        [0.2651, 0.2336, 0.5057]])


In [88]:
m+n

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [89]:
m.add_(n)

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [90]:
m

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [91]:
torch.relu(m)

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [92]:
m.relu_()

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

In [93]:
m

tensor([[1.8865, 1.2429, 1.6124],
        [0.6556, 0.4835, 0.8263]])

COPYING A TENSOR

In [94]:
a=torch.rand(2,3)
a

tensor([[0.5688, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [95]:
b=a

In [96]:
b

tensor([[0.5688, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [97]:
a[0][0]=0

In [98]:
a

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [99]:
b

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [100]:
id(a)

133629894497984

In [101]:
id(b)

133629894497984

In [102]:
b=a.clone()

In [103]:
a

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [104]:
b

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [105]:
a[0][0]=10

In [106]:
a

tensor([[10.0000,  0.0634,  0.8993],
        [ 0.2732,  0.3397,  0.1879]])

In [107]:
b

tensor([[0.0000, 0.0634, 0.8993],
        [0.2732, 0.3397, 0.1879]])

In [108]:
id(a)

133629894497984

In [109]:
id(b)

133629893424160

TENSOR OPERATION ON GPU

In [110]:
torch.cuda.is_available()

True

In [111]:
device=torch.device("cuda")
device

device(type='cuda')

In [112]:
# CREATING A NEW TENSOR ON GPU
x=torch.rand((2,3),device=device)
x

tensor([[0.3563, 0.0303, 0.7088],
        [0.2009, 0.0224, 0.9896]], device='cuda:0')

In [113]:
# MOVING AN EXISTING TENSOR TO GPU
a=torch.rand(2,3)
a

tensor([[0.5534, 0.2682, 0.9556],
        [0.9761, 0.5934, 0.3124]])

In [115]:
b=a.to(device)

In [116]:
b+5

tensor([[5.5534, 5.2682, 5.9556],
        [5.9761, 5.5934, 5.3124]], device='cuda:0')

In [120]:
import time

# DEFINE THE SIZE OF THE MATRICES
size=1000 #LARGE SIZE FOR PERFORMANCE COMPARSION

# CREATE RANDOM MATRICES ON CPU
matrix_cpu1=torch.rand(size,size)
matrix_cpu2=torch.rand(size,size)

# MEASURE THE TIME TAKEN TO MULTIPLY THE MATRICES ON CPU
start_time=time.time()
# MATIX MUTLIPICATION ON CPU
result_cpu=torch.matmul(matrix_cpu1,matrix_cpu2)
cpu_time=time.time()-start_time
print(f"Time taken for CPU multiplication: {cpu_time} seconds")

# MOVE MATRICES TO GPU
matrix_gpu1=matrix_cpu1.to(device)
matrix_gpu2=matrix_cpu2.to(device)

# MEASURE THE TIME TAKEN TO MULTIPLY THE MATRICES ON GPU
start_time=time.time()
# MATIX MUTLIPICATION ON GPU
result_gpu=torch.matmul(matrix_gpu1,matrix_gpu2)
torch.cuda.synchronize() # ENSURE ALL GPU OPERATIONS ARE COMPELETE
gpu_time=time.time()-start_time
print(f"Time taken for GPU multiplication: {gpu_time} seconds")

print(f"GPU is {cpu_time/gpu_time} times faster than CPU")

Time taken for CPU multiplication: 0.017346858978271484 seconds
Time taken for GPU multiplication: 0.0009746551513671875 seconds
GPU is 17.79794520547945 times faster than CPU


RESHAPING TENSORS

In [121]:
a=torch.ones(4,4)
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [122]:
# RESHAPE
a.reshape(2,2,2,2)

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [123]:
# FLATTEN
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [124]:
b=torch.rand(2,3,4)
b

tensor([[[0.0725, 0.4053, 0.6109, 0.6539],
         [0.2027, 0.0298, 0.9324, 0.9879],
         [0.1142, 0.5151, 0.3628, 0.9032]],

        [[0.8186, 0.7866, 0.6962, 0.8758],
         [0.4021, 0.4723, 0.8623, 0.9867],
         [0.9557, 0.2597, 0.4822, 0.2435]]])

In [125]:
#PERMUATE
b.permute(2,0,1)

tensor([[[0.0725, 0.2027, 0.1142],
         [0.8186, 0.4021, 0.9557]],

        [[0.4053, 0.0298, 0.5151],
         [0.7866, 0.4723, 0.2597]],

        [[0.6109, 0.9324, 0.3628],
         [0.6962, 0.8623, 0.4822]],

        [[0.6539, 0.9879, 0.9032],
         [0.8758, 0.9867, 0.2435]]])

In [126]:
# UNSQUEEZE
# IMAGE SIZE
c=torch.rand(226,226,3)
c

tensor([[[0.7711, 0.8058, 0.7985],
         [0.5763, 0.6000, 0.3298],
         [0.0215, 0.6231, 0.8445],
         ...,
         [0.5048, 0.4370, 0.3643],
         [0.0930, 0.8944, 0.2637],
         [0.2397, 0.3142, 0.7672]],

        [[0.0186, 0.8114, 0.6525],
         [0.5602, 0.6544, 0.3092],
         [0.9706, 0.9911, 0.6165],
         ...,
         [0.7550, 0.4344, 0.9511],
         [0.8181, 0.7376, 0.9000],
         [0.0333, 0.7595, 0.4717]],

        [[0.3631, 0.9723, 0.8389],
         [0.3497, 0.5625, 0.8555],
         [0.7586, 0.4285, 0.2075],
         ...,
         [0.0187, 0.1206, 0.8592],
         [0.6711, 0.9092, 0.2085],
         [0.7607, 0.5833, 0.9341]],

        ...,

        [[0.1169, 0.1945, 0.2781],
         [0.4409, 0.4445, 0.3152],
         [0.0592, 0.5148, 0.4397],
         ...,
         [0.8111, 0.2380, 0.5726],
         [0.7833, 0.7770, 0.0841],
         [0.8408, 0.7431, 0.2954]],

        [[0.0728, 0.7655, 0.1266],
         [0.5977, 0.0290, 0.9353],
         [0.

In [127]:
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [129]:
c.unsqueeze(1).shape

torch.Size([226, 1, 226, 3])

In [132]:
# SEQUEEZE
d=torch.rand(1,20)
print(d.shape)
d.squeeze(0).shape

torch.Size([1, 20])


torch.Size([20])

# NUMPY AND PYTORCH

In [133]:
import numpy as np

In [134]:
a=torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [135]:
b=a.numpy()
b

array([1, 2, 3])

In [136]:
type(b)

numpy.ndarray

In [137]:
c=np.array([1,2,3])
c

array([1, 2, 3])

In [138]:
torch.from_numpy(c)

tensor([1, 2, 3])